apiVersion: v1
kind: ConfigMap
metadata:
  name: st2sco-config
  namespace: st2sco
data:
  POSTGRES_DB: st2sco
  POSTGRES_USER: st2sco_user
  DATABASE_HOST: db
  DATABASE_PORT: "5432"
  DATABASE_NAME: st2sco
  NODE_ENV: production
